const roleRouter = require("./roleRouter");
const authRouter = require("./authRouter");
const DishesRouter = require("./DishesRouter");
const restaurantController = require("./restaurantRouter");
const DishCateRouter = require("./DishCateRouter");
const userRouter = require("./userRouter");
const supplierRoute = require("./supplierRoute");
const ingredientCategoryRoute = require("./ingredientCategoryRouter");
const ingredientRoute = require("./ingredientRouter");
const tableRouter = require("./tableRouter");
const comboRouter = require("./comboRouter");
const importInvoice = require("./importInvoiceRouter");
const importInvoiceDetail = require("./importInvoiceDetailRouter");
const dishIngredient = require("./dishIngredientRouter");
const reservation = require("./reservationRouter");
const order = require("./orderRouter");
const orderDetail = require("./orderDetailRouter");
const memberCard = require("./memberCardRouter");
const invoice = require("./invoiceRouter");
const dashboardRoute = require("./dashboardRouter");

const routes = (app) => {
  app.use("/v1/api/role", roleRouter);
  app.use("/v1/api", authRouter);
  app.use("/v1/api/user", userRouter);
  app.use("/v1/api/dish-category", DishCateRouter);
  app.use("/v1/api/restaurants", restaurantController);
  app.use("/v1/api/dishes", DishesRouter);
  app.use("/v1/api/supplier", supplierRoute);
  app.use("/v1/api/ingredient-category", ingredientCategoryRoute);
  app.use("/v1/api/ingredient", ingredientRoute);
  app.use("/v1/api/table", tableRouter);
  app.use("/v1/api/combo", comboRouter);
  app.use("/v1/api/import-invoice", importInvoice);
  app.use("/v1/api/import-invoice-detail", importInvoiceDetail);
  app.use("/v1/api/dish-ingredient", dishIngredient);
  app.use("/v1/api/reservation", reservation);
  app.use("/v1/api/order", order);
  app.use("/v1/api/order-detail", orderDetail);
  app.use("/v1/api/member-card", memberCard);
  app.use("/v1/api/invoice", invoice);
  app.use("/v1/api/dashboard", dashboardRoute);
};

module.exports = routes;
